# Generated by Django 4.1.3 on 2022-11-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartieAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='chefDepartement',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='chefdepartement',
            field=models.ManyToManyField(related_name='chefdepartement', to='PartieAdmin.departement'),
        ),
    ]
