# Generated by Django 4.1.3 on 2022-11-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartieAdmin', '0002_remove_enseignant_chefdepartement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='chefdepartement',
            field=models.ManyToManyField(blank=True, related_name='chefdepartement', to='PartieAdmin.departement'),
        ),
    ]
