# Generated by Django 4.1.3 on 2022-11-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartieAdmin', '0005_alter_enseignant_chefdepartement'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='heure',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
