# Generated by Django 4.1.3 on 2022-11-07 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PartieAdmin", "0007_alter_enseignant_chefdepartement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="element",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elements",
                to="PartieAdmin.module",
            ),
        ),
    ]
